import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nave from "./nav";
import Footer from "./footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Nave />
        <div className="min-h-fit mx-auto container grow">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
